version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: shippy_pg
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - shippy_pg:/var/lib/postgresql/data

volumes:
  shippy_pg:
